source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TwilioTest_Example', :exclusive => true do
  pod 'TwilioTest', :path => '../'
end

target 'TwilioTest_Tests', :exclusive => true do
  pod 'TwilioTest', :path => '../'

  
end
